---
- hosts: vms
  gather_facts: false
  connection: local
  user: remote
  become: true

  vars_files:
    - ../group_vars/vars
    - ../group_vars/vault

  tasks:
    - name: Create all VMs
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        esxi_hostname: "{{ esxi_host }}"
        datacenter: "{{ datacenter }}"
        folder: "{{ folder_name }}"
        name: "{{ inventory_hostname }}"
        template: "{{ vm_template }}"
        state: poweredon
        hardware:
          memory_mb: "{{ ram }}"
          num_cpus: "{{ cpus }}"

    - name: Add secondary disks
      vsphere_guest:
        vcenter_hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        guest: "{{ inventory_hostname }}"
        state: reconfigured
        vm_disk:
          disk2:
            size_gb: "{{ disk2_size }}"
            type: thin
            datastore: "{{ datastores | random }}"
      when: disk2_size is defined
