---
- hosts: docker
  gather_facts: false
  become_user: root
  become: true

  vars_files:
    - ../group_vars/vars

  vars:
    dtr_lb: "{{ groups['dtr_lb'][0] }}.{{ domain_name }}"

  environment: "{{ env }}"

  tasks:
    - name: Create Docker service directory
      file:
        path: /etc/systemd/system/docker.service.d
        state: directory
      notify: Restart Docker

    - name: Add proxy details
      template: src=../templates/http-proxy.conf.j2 dest=/etc/systemd/system/docker.service.d/http-proxy.conf
      when: env.http_proxy is defined or env.https_proxy is defined
      notify: Restart Docker

    - name: Add insecure registry
      lineinfile:
        path: /usr/lib/systemd/system/docker.service
        regexp: 'ExecStart=.*'
        line: 'ExecStart=/usr/bin/dockerd --insecure-registry {{ dtr_lb }}'
      notify: Restart Docker

    - meta: flush_handlers

    - name: Check if vsphere plugin is installed
      shell: docker plugin ls | grep vsphere | wc -l
      register: vsphere_installed

    - name: Install vsphere plugin
      command: docker plugin install --grant-all-permissions --alias vsphere store/vmware/docker-volume-vsphere:{{ vsphere_plugin_version }}
      when: vsphere_installed.stdout == "0"

    # Not sure if we need this step?
    #- name: Create volume
    #  command: docker volume create --driver=vsphere --name=MyVolume1

  handlers:
    - name: Restart Docker
      systemd:
        name: docker
        state: restarted
        daemon_reload: yes

