---
- hosts: docker
  gather_facts: false
  become_user: root
  become: true

  vars_files:
    - ../group_vars/vars

  environment: "{{ env }}"

  tasks:
    - name: Enable extras RHEL repository
      shell: yum-config-manager --enable rhel-7-server-extras-rpms

    - name: Install dependencies
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - policycoreutils-python 
        - libseccomp 
        - libtool-ltdl 
        - yum-utils
        - NetworkManager-glib 
        - nm-connection-editor
        - libsemanage-python 
        - policycoreutils-python

    - name: Set Docker url
      shell: echo {{ docker_ee_url }}/rhel > /etc/yum/vars/dockerurl

    - name: Set Docker version
      shell: echo {{ rhel_version }}  > /etc/yum/vars/dockerosversion

    - name: Add Docker repository
      command: yum-config-manager --add-repo {{ docker_ee_url }}/rhel/docker-ee.repo

    - name: Install Docker
      yum:
        name: docker-ee
        state: latest
        update_cache: yes
