---
- hosts: dtr
  gather_facts: false
  become_user: root
  become: true

  vars_files:
    - ../group_vars/vars
    - ../group_vars/vault

  vars:
    dtr_lb: "{{ groups['dtr_lb'][0] }}.{{ domain_name }}"
    ucp_main: "{{ groups['ucp_main'][0] }}.{{ domain_name }}"
    dtr_main: "{{ groups['dtr_main'][0] }}"
    nfs_server: "{{ hostvars[groups['nfs'][0]].ip_addr | ipaddr('address') }}"

  tasks:
    - name: Open required ports for DTR
      command: firewall-cmd --permanent --zone=public --add-port=80/tcp --add-port=443/tcp --add-port=2377/tcp --add-port=4789/tcp --add-port=4789/udp --add-port=7946/tcp --add-port=7946/udp --add-port=12376/tcp

    - name: Reload firewalld configuration
      command: firewall-cmd --reload

    - name: Get worker token
      include_vars:
        file: /tmp/worker_token
        name: add_worker

    - name: Check if node already belongs to the swarm
      shell: docker info | grep "Swarm{{':'}} inactive" | wc -l
      register: swarm_inactive

    - name: Add DTR nodes to the swarm
      command: "{{ add_worker.token }}"
      when: swarm_inactive.stdout == "1"

    - name: Install first DTR node
      command: docker run --rm docker/dtr:{{ dtr_version }} install --nfs-storage-url nfs://{{ nfs_server }}{{ images_folder }} --ucp-node {{ inventory_hostname }}.{{ domain_name }} --ucp-insecure-tls --dtr-external-url https://{{ dtr_lb }} --ucp-url https://{{ ucp_main }} --ucp-username {{ ucp_username }} --ucp-password {{ ucp_password }}
      when: inventory_hostname in groups.dtr_main and swarm_inactive.stdout == "1"
      register: dtrlog
      until: dtrlog.rc == 0
      retries: 20
      delay: 20

    - name: Get replica ID
      shell: docker ps --format "{{ '{{' }}.Names{{ '}}' }}" | grep dtr | awk -F'-' '{ print $NF }' | uniq
      register: replica_id
      when: inventory_hostname in groups.dtr_main

    - name: Add DTR nodes
      command: docker run --rm docker/dtr:{{ dtr_version }} join --ucp-node {{ inventory_hostname }}.{{ domain_name }} --ucp-url https://{{ ucp_main }} --ucp-username {{ ucp_username }} --ucp-password {{ ucp_password }} --ucp-insecure-tls --existing-replica-id {{ hostvars[dtr_main]['replica_id']['stdout'] }} 
      register: task_result
      until: task_result.rc == 0
      retries: 20
      delay: 60
      when: inventory_hostname not in groups.dtr_main and swarm_inactive.stdout == "1"

    - name: Enable image scanning
      uri:
        url: "https://{{ inventory_hostname }}/api/v0/meta/settings"
        method: POST
        user: "{{ ucp_username }}"
        password: "{{ ucp_password }}"
        body: {"scanningEnabled":true}
        status_code: 200
        body_format: json
        force_basic_auth: yes
        validate_certs: no
      when: inventory_hostname in groups.dtr_main
